os: osx
language: objective-c
osx_image: xcode10.1
sudo: false
env:
  global:
  - THEOS=~/theos
before_install:
- brew install dpkg ldid
- git clone --recursive git://github.com/theos/theos.git ~/theos
script:
- make clean package FINALPACKAGE=1
before_deploy:
- export RELEASE_PKG_FILE=$(ls ./packages/*.deb)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "ZUrFJ0ihN5TA9Owj8a0lvKG0DfToVr8R6AitEUWjixSXlucIKefy3154TY89vHhW+9KuGPn7QARcwfQMEegoUDPmxTMsKPxxi0aG9YMMGPUsdgew0+BcmumE4uQ9Qa2UqrG2aFO2O5Y4C4o2HRevFKbwuYp7spDb0bqxLbB8fBptmheoQmMqWCNoviGG3/AI8pccMOImpQGIJvBbnKb1XDxRkAESir2nV7Pk8Iaq9nFmTKrPKOkpmJpf4K7CSUgq8XqzrateEDSkYbTmqC1QeUMmwfS2YtEs1sqrT/mQ1npqHbWQb+GwKqr59n9qaJBScTpIlgMdxIQFrZhyP10ReOrLEauSvFca0D88/aZ7O70vPX6ujKRp2qal2CSaI5Vf8MDCvtCLC/jPHKugQ5xCSwXXpcM3R8DITjonASywr56cXwuZtj9YdQ41Xmybe2abhcyA6jFDwEBfffwhgkjerm4WVp3QKL4925o1LxRcP8uDnV5S9Su/72IMukeJWPoMLlpWBvGUTSIZVNdEvuClsrToU7IEp+BYVUABTWpkBL4QYlLeoSwseiXnhZsX8yniQGpaN+5u/j0wxbnHDmVtLyRSQMB7+yXksEAmB6StUUVuD2eaoUO15qC+z0W9jZl7lMqD+V2DADsnjh41ttHXkdDmStxVT9g0jFDoFtlArAU="
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  on:
    repo: EvanDbg/HardRespring
    branch: main
